spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}